import { env } from "cloudflare:workers";
import { getGoogleUser } from "../../google-auth";
import { isEarlyAccessAdmin } from "../../early-access-policy";
import { clientIp, enforceApiRateLimit, isSameOrigin } from "../security";

type FeedbackRow={id:string;reporter_email:string|null;team_id:number|null;category:string;message:string;page_url:string|null;status:string;created_at:string;resolved_at:string|null};
async function ensureTable(){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS feedback_reports (id TEXT PRIMARY KEY,reporter_email TEXT,team_id INTEGER,category TEXT NOT NULL,message TEXT NOT NULL,page_url TEXT,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL,resolved_at TEXT)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_feedback_reports_status_created ON feedback_reports(status,created_at)")])}
const validEmail=(value:string)=>/^\S+@\S+\.\S+$/.test(value)&&value.length<=254;

export async function GET(){const user=await getGoogleUser();if(!user||!isEarlyAccessAdmin(user.email))return Response.json({error:"Administrator access required"},{status:403});await ensureTable();const rows=await env.DB.prepare("SELECT id,reporter_email,team_id,category,message,page_url,status,created_at,resolved_at FROM feedback_reports ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END,created_at DESC LIMIT 200").all<FeedbackRow>();return Response.json({reports:rows.results})}
export async function POST(request:Request){
  if(!isSameOrigin(request))return Response.json({error:"Invalid request origin"},{status:403});if(Number(request.headers.get("content-length")??"0")>8_192)return Response.json({error:"Report is too large"},{status:413});
  const user=await getGoogleUser();const body=await request.json().catch(()=>null) as {category?:unknown;message?:unknown;pageUrl?:unknown;email?:unknown;teamId?:unknown}|null;
  const category=String(body?.category??"");const message=String(body?.message??"").trim();const pageUrl=String(body?.pageUrl??"").trim();const supplied=String(body?.email??"").trim().toLowerCase();const identityEmail=user&&!user.email.endsWith("@member.wicketsplit.local")?user.email.toLowerCase():null;const reporterEmail=identityEmail??(validEmail(supplied)?supplied:null);const teamId=Number(body?.teamId)||null;
  if(!["problem","suggestion","question"].includes(category)||message.length<10||message.length>2_000||pageUrl.length>500||(!user&&!reporterEmail))return Response.json({error:"Add a valid email and at least 10 characters of detail"},{status:400});
  if(teamId&&user){const member=await env.DB.prepare("SELECT 1 AS ok FROM team_memberships WHERE team_id=? AND email=?").bind(teamId,user.email.toLowerCase()).first<{ok:number}>();if(!member)return Response.json({error:"Invalid team"},{status:403})}
  const key=identityEmail??reporterEmail??clientIp(request);const allowed=await enforceApiRateLimit(`feedback:${key}`,10,24*60*60*1000)&&await enforceApiRateLimit(`feedback-ip:${clientIp(request)}`,30,24*60*60*1000);if(!allowed)return Response.json({error:"Too many reports. Try again tomorrow."},{status:429});
  await ensureTable();const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO feedback_reports(id,reporter_email,team_id,category,message,page_url,status,created_at) VALUES(?,?,?,?,?,?,'open',?)").bind(id,reporterEmail,teamId,category,message,pageUrl||null,new Date().toISOString()).run();return Response.json({ok:true,id});
}
export async function PATCH(request:Request){if(!isSameOrigin(request))return Response.json({error:"Invalid request origin"},{status:403});const user=await getGoogleUser();if(!user||!isEarlyAccessAdmin(user.email))return Response.json({error:"Administrator access required"},{status:403});const body=await request.json().catch(()=>null) as {id?:unknown;status?:unknown}|null;const id=String(body?.id??"");const status=String(body?.status??"");if(!id||!["open","resolved"].includes(status))return Response.json({error:"Invalid feedback update"},{status:400});await ensureTable();await env.DB.prepare("UPDATE feedback_reports SET status=?,resolved_at=? WHERE id=?").bind(status,status==="resolved"?new Date().toISOString():null,id).run();return Response.json({ok:true})}
