"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { FormEvent, useState } from "react";

export default function RequestAccess(){
  const [name,setName]=useState("");const [email,setEmail]=useState("");const [teamName,setTeamName]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/early-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,teamName,note})});const result=await response.json().catch(()=>({})) as {error?:string};setBusy(false);if(!response.ok){setError(result.error??"Your request could not be submitted.");return}setDone(true)};
  return <main className="early-access-page"><section className="early-access-card"><a className="public-brand" href="/"><span>W</span>WicketSplit</a><span className="hero-kicker">INVITE-ONLY EARLY ACCESS</span>{done?<><h1>Request received.</h1><p>Thanks, {name}. We’ll review the request for <strong>{teamName}</strong>. If approved, we’ll send a private signup link to <strong>{email}</strong>.</p><div className="early-access-note">You do not need to create an account yet. The approval link will be tied to this email and valid for seven days.</div></>:<><h1>Tell us about your team.</h1><p>Request early access with your email and team name. No account or card is required.</p><form onSubmit={submit}><label>Your name<input autoFocus required maxLength={160} autoComplete="name" value={name} onChange={event=>setName(event.target.value)} placeholder="Your name"/></label><label>Email address<input required maxLength={254} type="email" inputMode="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com"/></label><label>Team name<input required maxLength={160} value={teamName} onChange={event=>setTeamName(event.target.value)} placeholder="e.g. Wolfpacks"/></label><label>How would you use WicketSplit? <span>Optional</span><textarea maxLength={800} value={note} onChange={event=>setNote(event.target.value)} placeholder="League size, number of players, or what you want to track"/></label><button className="primary" disabled={busy}>{busy?"Sending…":"Request early access →"}</button>{error&&<div className="early-access-error">{error}</div>}</form></>}<div className="early-access-footer"><a href="/login?return_to=/app">Already approved? Sign in</a><a href="/">Back to homepage</a></div></section></main>;
}
