"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { FormEvent, useMemo, useState } from "react";

type Player={id:number;name:string};

export default function JoinTeam(){
  const token=useMemo(()=>typeof window!=="undefined"?new URLSearchParams(window.location.search).get("token")??"":"",[]);
  const [pin,setPin]=useState("");const [teamName,setTeamName]=useState("");const [players,setPlayers]=useState<Player[]>([]);const [playerId,setPlayerId]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const request=async(body:{token:string;pin:string;playerId?:number})=>{const response=await fetch("/api/team-access/join",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json().catch(()=>({})) as {error?:string;teamName?:string;players?:Player[]};if(!response.ok)throw new Error(result.error??"Team access could not be completed");return result};
  const verify=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const result=await request({token,pin});const roster=result.players??[];setTeamName(result.teamName??"Team");setPlayers(roster);setPlayerId(roster[0]?.id??0)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const join=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{await request({token,pin,playerId});location.assign("/app")}catch(reason){setError((reason as Error).message);setBusy(false)}};
  return <main className="member-join-page"><section className="member-join-card"><a className="public-brand" href="/"><span>W</span>WicketSplit</a>{players.length?<form onSubmit={join}><span className="hero-kicker">{teamName.toUpperCase()}</span><h1>Choose your player</h1><p>Your Home page and submitted expenses will use the roster player selected here on this device.</p><label>Your roster name<select autoFocus value={playerId} onChange={event=>setPlayerId(Number(event.target.value))}>{players.map(player=><option key={player.id} value={player.id}>{player.name}</option>)}</select></label>{error&&<div className="login-error">{error}</div>}<button className="primary" disabled={busy||!playerId}>{busy?"Opening team…":"Open my team →"}</button><button type="button" className="member-change-pin" onClick={()=>{setPlayers([]);setError("")}}>Use a different PIN</button></form>:<form onSubmit={verify}><span className="hero-kicker">TEAM MEMBER ACCESS</span><h1>Join your team</h1><p>Enter the private 6-digit PIN sent by your treasurer. You do not need to create an account.</p><label>Team PIN<input autoFocus required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000"/></label>{!token&&<div className="login-error">This team link is incomplete. Ask your treasurer to copy it again.</div>}{error&&<div className="login-error">{error}</div>}<button className="primary" disabled={busy||pin.length!==6||!token}>{busy?"Checking…":"Continue →"}</button></form>}<small>Shared member access lets players view team records and add expenses they paid. Do not forward the private link or PIN.</small></section></main>;
}
