"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect,useState } from "react";

type AccessRequest={email:string;name:string;team_name:string;note:string;status:"pending"|"approved"|"rejected";requested_at:string};

export default function EarlyAccessAdmin(){
  const [requests,setRequests]=useState<AccessRequest[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [admin,setAdmin]=useState(false);const [copied,setCopied]=useState("");
  useEffect(()=>{let active=true;fetch("/api/early-access").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not load requests");if(active){setAdmin(Boolean(result.isAdmin));setRequests(result.requests??[])}}).catch(reason=>{if(active)setError((reason as Error).message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const update=async(email:string,status:AccessRequest["status"])=>{const response=await fetch("/api/early-access",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({email,status})});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Access could not be updated");return}setRequests(current=>current.map(item=>item.email===email?{...item,status}:item))};
  const approvalMessage=(item:AccessRequest)=>`Hi ${item.name},\n\nYour early access to WicketSplit has been approved for ${item.team_name}.\n\nSign in using ${item.email}:\n${location.origin}/login?return_to=/app\n\nAfter signing in, WicketSplit will guide you through creating your team and first league. Please use the same approved email address.\n\nI’d love to hear your feedback after you try it.`;
  const copyApproval=async(item:AccessRequest)=>{setError("");try{await navigator.clipboard.writeText(approvalMessage(item));setCopied(item.email);setTimeout(()=>setCopied(current=>current===item.email?"":current),2200)}catch{setError("The message could not be copied. Check your browser clipboard permission.")}};
  return <main className="early-admin-page"><nav className="legal-nav"><a className="public-brand" href="/"><span>W</span>WicketSplit</a><a href="/app">Open workspace →</a></nav><section className="early-admin-shell"><span className="hero-kicker">CONTROLLED ROLLOUT</span><h1>Early-access requests</h1><p>Approve only the teams you want to onboard. After approval, copy the ready-to-send message and share it by email, WhatsApp, or LinkedIn.</p>{loading?<div className="early-admin-empty">Loading requests…</div>:!admin?<div className="early-admin-empty">This page is available only to the WicketSplit early-access administrator.</div>:requests.length?<div className="early-request-list">{requests.map(item=><article key={item.email}><div><strong>{item.name}</strong><span>{item.email}</span><b>{item.team_name}</b>{item.note&&<p>{item.note}</p>}<small>Requested {new Date(item.requested_at).toLocaleDateString()}</small></div><div><span className={`access-status ${item.status}`}>{item.status}</span>{item.status==="approved"?<button className="primary copy-approval" onClick={()=>copyApproval(item)}>{copied===item.email?"✓ Message copied":"Copy approval message"}</button>:<button className="primary" onClick={()=>update(item.email,"approved")}>Approve</button>}<button className="ghost" disabled={item.status==="rejected"} onClick={()=>update(item.email,"rejected")}>Reject</button></div></article>)}</div>:<div className="early-admin-empty">No early-access requests yet.</div>}{error&&<div className="early-access-error">{error}</div>}</section></main>;
}
