/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { useEffect,useState } from "react";
type Report={id:string;reporter_email:string|null;team_id:number|null;category:string;message:string;page_url:string|null;status:"open"|"resolved";created_at:string};
export default function FeedbackAdmin(){
  const [reports,setReports]=useState<Report[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);const load=()=>fetch("/api/feedback").then(async response=>{const result=await response.json() as {error?:string;reports?:Report[]};if(!response.ok)throw new Error(result.error??"Could not load reports");setReports(result.reports??[])}).catch(reason=>setError((reason as Error).message)).finally(()=>setLoading(false));useEffect(()=>{void load()},[]);
  const update=async(report:Report)=>{const status=report.status==="open"?"resolved":"open";const response=await fetch("/api/feedback",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:report.id,status})});if(response.ok)setReports(current=>current.map(item=>item.id===report.id?{...item,status}:item));else setError("Feedback status could not be updated")};
  return <main className="early-admin-page"><nav className="legal-nav"><a className="public-brand" href="/"><span>W</span>WicketSplit</a><a href="/app">Open workspace →</a></nav><section className="early-admin-shell"><span className="hero-kicker">BETA OPERATIONS</span><h1>Feedback reports</h1><p>Problems, suggestions, and questions submitted through WicketSplit.</p>{loading?<div className="early-admin-empty">Loading reports…</div>:reports.length?<div className="feedback-report-list">{reports.map(report=><article key={report.id} className={report.status}><div><span className="access-status">{report.category}</span><strong>{report.reporter_email??"Team-link player"}</strong><small>{new Date(report.created_at).toLocaleString()}{report.team_id?` · Team ${report.team_id}`:""}</small><p>{report.message}</p>{report.page_url&&<a href={report.page_url} target="_blank" rel="noopener noreferrer">Reported page ↗</a>}</div><button className={report.status==="open"?"primary":"ghost"} onClick={()=>update(report)}>{report.status==="open"?"Mark resolved":"Reopen"}</button></article>)}</div>:<div className="early-admin-empty">No feedback reports yet.</div>}{error&&<div className="early-access-error">{error}</div>}</section></main>;
}
