/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { FormEvent,useEffect,useState } from "react";
type Team={id:number;name:string};
export default function FeedbackForm({signedIn,email:initialEmail}:{signedIn:boolean;email:string}){
  const [email,setEmail]=useState(initialEmail),[category,setCategory]=useState("problem"),[message,setMessage]=useState(""),[teams,setTeams]=useState<Team[]>([]),[teamId,setTeamId]=useState(0),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");useEffect(()=>{if(!signedIn)return;fetch("/api/state").then(response=>response.ok?response.json() as Promise<{teams?:Team[]}>:null).then(result=>{const next=result?.teams??[];setTeams(next);setTeamId(next[0]?.id??0)}).catch(()=>undefined)},[signedIn]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,category,message,teamId:teamId||undefined,pageUrl:document.referrer||location.href})});const result=await response.json().catch(()=>({})) as {error?:string};setBusy(false);if(!response.ok){setError(result.error??"Report could not be sent");return}setDone(true)};
  return <main className="utility-page"><section className="utility-card feedback-card"><a className="public-brand" href="/"><span>W</span>WicketSplit</a><span className="hero-kicker">BETA FEEDBACK</span>{done?<><h1>Thanks—we received it.</h1><p>Your report is now in the WicketSplit beta review queue.</p><a className="primary" href={signedIn?"/app":"/"}>Return to WicketSplit</a></>:<><h1>Report a problem</h1><p>Tell us what happened, what you expected, and which screen you were using. Please do not include passwords, PINs, or private invitation links.</p><form onSubmit={submit}>{!initialEmail&&<label>Email<input required type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label>}{teams.length>0&&<label>Team (optional)<select value={teamId} onChange={event=>setTeamId(Number(event.target.value))}><option value="0">General feedback</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label>}<label>Type<select value={category} onChange={event=>setCategory(event.target.value)}><option value="problem">Something is not working</option><option value="suggestion">Feature suggestion</option><option value="question">Question</option></select></label><label>Details<textarea required minLength={10} maxLength={2000} value={message} onChange={event=>setMessage(event.target.value)} placeholder="What happened? What did you expect instead?"/></label><button className="primary" disabled={busy}>{busy?"Sending…":"Send report →"}</button>{error&&<div className="early-access-error">{error}</div>}</form><div className="utility-footer"><a href={signedIn?"/app":"/"}>← Go back</a><a href="/privacy">Privacy</a></div></>}</section></main>;
}
