/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { useEffect,useState } from "react";
type Team={id:number;name:string;access?:{isOwner?:boolean}};
export default function BackupClient(){
  const [teams,setTeams]=useState<Team[]>([]),[teamId,setTeamId]=useState(0),[backup,setBackup]=useState<unknown>(null),[fileName,setFileName]=useState(""),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const team=teams.find(item=>item.id===teamId);
  useEffect(()=>{fetch("/api/state").then(async response=>{if(!response.ok)throw new Error("Could not load teams");return response.json() as Promise<{teams?:Team[]}>}).then(result=>{const next=result.teams??[];setTeams(next);setTeamId(next[0]?.id??0)}).catch(error=>setMessage((error as Error).message))},[]);
  const chooseFile=async(file?:File)=>{setMessage("");setBackup(null);setFileName("");if(!file)return;if(file.size>400_000){setMessage("That backup is too large.");return}try{setBackup(JSON.parse(await file.text()));setFileName(file.name)}catch{setMessage("Choose a valid WicketSplit JSON backup.")}};
  const restore=async()=>{if(!team||!backup)return;setBusy(true);setMessage("");const response=await fetch("/api/backup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamId:team.id,confirmation,backup})});const result=await response.json().catch(()=>({})) as {error?:string};setBusy(false);if(!response.ok){setMessage(result.error??"Restore failed");return}setMessage("Backup restored. The previous team version was also saved as a server recovery point.");setBackup(null);setFileName("");setConfirmation("")};
  return <main className="utility-page"><section className="utility-card backup-card"><a className="public-brand" href="/"><span>W</span>WicketSplit</a><span className="hero-kicker">BETA DATA SAFETY</span><h1>Backup & recovery</h1><p>Download a portable copy of a team before major changes. Restoring replaces roster, leagues, games, expenses, credits, and payments—but keeps memberships, invitations, and team access unchanged.</p><label>Team<select value={teamId} onChange={event=>{setTeamId(Number(event.target.value));setConfirmation("");setBackup(null)}}>{teams.map(item=><option key={item.id} value={item.id}>{item.name}{item.access?.isOwner===false?" (co-treasurer)":""}</option>)}</select></label><div className="backup-actions"><div><strong>1. Download current backup</strong><small>Available to owners and co-treasurers.</small><a className="primary" href={team?`/api/backup?teamId=${team.id}`:"#"}>Download JSON backup</a></div><div className={!team||team.access?.isOwner===false?"restore-disabled":""}><strong>2. Restore a backup</strong><small>Owner only. A server recovery point is created first.</small><label className="file-picker">{fileName||"Choose backup file"}<input type="file" accept="application/json,.json" disabled={!team||team.access?.isOwner===false} onChange={event=>chooseFile(event.target.files?.[0])}/></label>{Boolean(backup)&&<><label>Type <b>{team?.name}</b> to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="danger-action" disabled={busy||confirmation!==team?.name} onClick={restore}>{busy?"Restoring…":"Restore this backup"}</button></>}</div></div>{message&&<div className="utility-message">{message}</div>}<div className="utility-footer"><a href="/app">← Return to workspace</a><a href="/feedback">Report a problem</a></div></section></main>;
}
